### ISSUE TITLE
Allow evaluating arbitrary shell text in .envrc

### ISSUE THREAD

**Issue by mcandre** [direnv/direnv#196]
I use a lot of different shell switchers, including jenv, gvm, rvm, and nvm. Of course, each of these slow down my bash shell :(

I'd love to be able to use direnv to only load the necessary tools in {jenv,gvm,rvm,nvm} per project, and unload them when leaving the project directory. How can we extend direnv to accomplish this?

**Comment by mcandre** [comment]
Ah, I think I understand how this works!

**Comment by zimbatm** [comment]
Great !

Just to be sure because not everyone seem to see it, there is a set of functions available in the context of the envrc called the "stdlib". It's all the functions over there: https://github.com/direnv/direnv/blob/master/stdlib.sh#L389-L411
The ones highlighted should give you an idea of how to integrate other environment switchers. Once you've designed your own put them in a `~/.direnvrc` file to make it available everywhere on your computer. If you think one of your function is generic enough and could be used by others I'm happy to add them to the stdlib.

Best,
z
