### ISSUE TITLE
ENV not modified when command runs part of direnv allow

### ISSUE THREAD

**Issue by gerhard** [direnv/direnv#221]
If I run a command on the same line as `direnv allow`, the ENV won't be modified correctly, e.g.:

```sh
$ direnv allow && echo $GOPATH
/root/go
direnv: loading .envrc
direnv: export ~GOPATH
$ echo $GOPATH
/tmp/build/ab682a4b/git-bosh-release:/root/go
```

The same applies if I run `direnv allow` in a script. The ENV won't be modified by direnv until the script exits.

How can I ensure that anything running in the same context as `direnv allow` runs with a modified env?

**Comment by zimbatm** [comment]
direnv depends on the "before prompt" hook to load the environment. Because `echo $GOPATH` is executed before the prompt, direnv hasn't had the chance to do it's thing yet. It's the same in a script, since there is no prompt direnv will never execute.

But don't despair, it's always possible to execute the code outside of the hook.
If you want to load the new environment by hand, execute `eval "$(direnv export bash)"` which will do the same as if a new prompt had been shown.
