### ISSUE TITLE
commands with non-zero exit codes in .envrc

### ISSUE THREAD

**Issue by agibralter** [direnv/direnv#245]
Is it possible to run a command that may have a non-0 exit code in an .envrc?

I'm trying to do something like:

```shell
my_command &>/dev/null
if [ $? -eq 0]; then
  # something
else
  # something else
fi
```

I'm getting `direnv: error exit status 1` instead of "something else"

Thanks!

**Comment by zimbatm** [comment]
This is because `set -e` is activated in the `.envrc` sub-shell. When that is set, the script terminates if any expression returns with an exit status bigger than zero. It's useful to make that a script will not silently fail as you noticed.

If you only need to switch on zero vs non-zero exit status command, the easies is to use:

```bash
if my_command &>/dev/null; then
  # exit_status is zero
else
  # exit_statis is > 0
fi
```

In fact the `[ ]` syntactic sugar does the same thing. If you run:
```
[ 1 -eq 2 ]
echo $?
````
you should see the exit status being 1

**Comment by agibralter** [comment]
Ahh, makes sense. Thank you! (Might it be helpful to have some documentation on that?)

**Comment by zimbatm** [comment]
Yeah I should probably add a reference to the bash manual
