### ISSUE TITLE
direnv allow - bypassing if using source_env/source_up in .envrc

### ISSUE THREAD

**Issue by seffenberg-naspers** [direnv/direnv#249]
Maybe I'm only expecting something weird, but right now all `.envrc` files needs to be allowed to be executed directly, but as soon as the `.envrc` has a `source_env` or `source_up` directive the related `.envrc` which should be loaded isn't checked (direnv version v2.9.0) for being allowed.

This means the `direnv allow` for such a file is like a placebo effect and can be bypassed without any problem. I was actually expecting direnv to check also the sourced file to be allowed.

**Comment by seffenberg-naspers** [comment]
alternatively it might be also useful to somehow store not only the hash of the`.envrc` which was allowed by `direnv allow` but also storing all the related hashes of all `.envrc` files sources at `direnv allow` time and invalidate the `.envrc` also if any of the subfiles changed. This would make it unnecessary to `direnv allow` each and all subsequent files.

**Comment by zimbatm** [comment]
Yes that's the current design. I'm expecting the user to be responsible for checking the whole chain before allowing the `.envrc`. The goal of the security framework is mostly to avoid situations where the user `git pull` a repo and gets arbitrary code executed :)

**Comment by seffenberg-naspers** [comment]
but then it is not really a security framework, isn't it? Because if you don't check the whole chain to not being changed it doesn't matter if you change the main file or not. So it would only mean to "enable" a directory and not "allow" it.. as soon as you include something via `source_up/source_env` you can stop carrying about any change in the main `.envrc` as well because it is insecure by design, isn't it?

**Comment by zimbatm** [comment]
Then give me a specific scenario and then we can discuss. So far I am seeing a danger but it doesn't remove the value of the existing protection and doesn't seem more risky than loading other people's bash code or build scripts.

In the scenario I have in mind, the attacker would somehow convince you to `direnv allow` the `.envrc` that he checked into his project and that loads another file (which I don't recommend doing, direnv is a personal tool). And some time later, push an update to the other file that you would forget to check on the next `git pull`. This would probably result in burning his github identity. With the same reasoning I think the attacker could as well push a change to the project's build script.

**Comment by seffenberg-naspers** [comment]
For me it doesn't matter that much how the fake code can come into my system. It is more of a concept thinking. If I `allow` something, then I have the whole chain in mind and not the single file. Otherwise the command `allow` is here misleading in my opinion, because it is more an `enable` as long as any other `.envrc` is being sourced than the main one. It's like having a fingerprint reader on my front door but my back-door is not having a lock at all.

Or maybe tell me why you still test the content of the file of being changed as long as you have any `source_up/source_env` inside of it? Because it is like testing half of it. What do you try to prevent in that case? Any mistake somebody did? Or is it for security reasons? If it is the latter, than it is not secure because the `attacker` only have to change one of the sourced files and this works. If it is for safety because somebody might do a mistake it is the same problem. And if you say it is a `pesonal tool` than why re-checking after you `enabled` it once? Because you should know what you `git pull` (like your argument: you have to check your whole chain).

Don't get me wrong, I just want to make clear, that I really didn't expect that behavior. At least a big note on the `source_env/up` command saying:
> this will not being tested for changes and doesn't have to be allowed in anyway, so be careful while using this
is something I would request.

But personally I would prefer a chain of trust.. (because I'm lazy and don't wanna test the git repository I pull multiple times from ;) )

**Comment by zimbatm** [comment]
Ok duly noted :)

Implementation wise it's a bit difficult because the second envrc is only
discovered at evaluation time. It makes it hard to present a list of files
to allow in one go to the user. Do you think that direnv should fail on
each step of the discovery ?

I think that if this get addressed then other questions will come up. For
example a similar attack could be mounted where the envrc executes a script
in the same folder. Because the script is not vetted by the security
framework it could also change over time.

**Comment by seffenberg-naspers** [comment]
Hmm, you're right, it is indeed like that (PATH_add would be a famous attack I guess). 

So I think `direnv` should (if possible, because I know it wouldn't be easy) only ensure the integrity of it's own "framework" and I count `source_up/_env` to this part.
The best way (to also keep it somehow similar to the actual behavior) would be (but this is only a "I would love to have ;) ):

`direnv allow` will create a file for this `.envrc` which also includes all subsequent `.envrc` file hashes. But this means that it would need to analyze the content and find all `source_up/env` stuff and check these files as well.

To be honest, this is not an easy change at all so for me it would be (for now, maybe thinking about this in a bigger scope sometime later) fine if at least the documentation would state this next to the explanation of `source_up/env` so that nobody expect this to be checked or requires to be `allowed` as well.

**Comment by zimbatm** [comment]
Yeah to make that a nice user experience I would basically have to move away from bash as the language for the `.envrc`. Or write a bash parser.

I added some warning to the documentation for now and closing this issue as I don't intend to implement the "full security".

Thanks for taking the time to discuss and provoking my point of view :)

**Comment by seffenberg-naspers** [comment]
thanks!

**Comment by dan-passaro** [comment]
What is the issue with simply having recursive failures if you have a recursive envrc structure? If I have a chain of three files and I have to issue three `direnv allow` commands, that is perhaps mildly annoying but, in my opinion, much better than not doing any checking at all. I will most likely have to `allow` them one-by-one anyway, assuming some kind of nested directory .envrc structure.

> I think that if this get addressed then other questions will come up. For
example a similar attack could be mounted where the envrc executes a script
in the same folder. Because the script is not vetted by the security
framework it could also change over time.

But this caveat already exists as-is in the current implementation, disregarding source_env.  Imo this shouldn't be a barrier to applying security to source_env/source_up. The issue is if I have checked my .envrc to make sure it's *not* doing anything troublesome like running an arbitrary script, but someone else has changed a different .envrc that I reference, I can still be compromised.

I can come up with one potential scenario where this is bad, but it's a bit of a stretch... If I'm working on a project, I might perhaps have my own specialized .envrc in the `tests/` subdirectory where I reference the .envrc in the parent dir. If someone malicious can change the contents of the parent .envrc, all I have to do to execute their shell code is `git pull` (and change dirs?) while I'm working on tests. Perhaps the source code is in a `src/` directory where I also have some overrides, making it a bit easier to fall into. And if that `src/` directory contains, say, the Django `manage.py` file, and you're on a large project using direnv, you might have a pretty good shot of pulling off RCE.

Now of course, wouldn't someone notice e.g. a random commit? If someone can write to your repo, couldn't they do something much worse, like touch your production code?

I'm not a blackhat and I'm not very good at imagining these scenarios. But I have seen plenty of extremely creative exploits to the point where the fact that this hole exists makes me uneasy, especially in a tool whose job is to automatically execute code. I've only ever had a chain of two .envrc files at the most, so `direnv allow` on both of them if they both change is not a big burden for me, and seems worth it to close this tiny and perhaps impossible/impractical attack vector.

If this is an acceptable change for the tool I'd be happy to furnish a PR.

**Comment by mrmachine** [comment]
I think this is a serious flaw and was very surprised to find that higher up `.envrc` files are not checked at all. I wasted some time testing that this was truly the case before coming here to report a bug.

At the very least, the warnings previously added are insufficient. The docs that describe the `source_env` and `source_up` features need to warn about this:

https://github.com/direnv/direnv#loading-layered-envrc

**Comment by zimbatm** [comment]
@mrmachine if you have a better suggestion on how to implement this I'm all ears. Here is a PR that improves the wording, let me know what you think: https://github.com/direnv/direnv/pull/463

**Comment by thernstig** [comment]
@zimbatm I found this issue when reading that source_env is not checked by the security framework and wanted to ask you something.

We've got a project where we work in teams in completely different environments currently. Some has to set a lot of env. vars. to get up and running. As we want everything to "just work" when someone clones or rebases in the repo, I thought out this scenario which I had hoped worked (but it seems it does not):

1. Commit two files called .envrc.devenv1 and .envrc.devenv2 that contains defaults for each environment.
2. Ask everyone to create a .envrc where they do source_env FILE (where file is either of the two).

My _hope_ with this would have been that if some senior maintainer updates either of these two files with new defaults, a user would rebase and then get a warning to allow them again. The good thing if this had worked would have been that direnv would have picked up new changes without having to send out an email to users saying "now you need to update your environment again".

So this is a scenario that is very real for us. But from what I can gather from this issue, this will not be possible since you only ever source the .envrc file so changes in the other two will never be noticed and picked up.

**Comment by vergenzt** [comment]
Hey @zimbatm I've found what seems to work reasonably well in the short term to accomplish the "iterative approval" security approach described earlier by @dan-passaro @ https://github.com/direnv/direnv/issues/249#issuecomment-284924908.

Do you see any issues with doing the following at the beginning of an `.envrc` file?

```bash
# recursively run direnv export in parent dir without DIRENV_* state vars
eval "$(env -uDIRENV_{DIR,FILE,WATCHES,DIFF} -C.. direnv export bash)"
```

Seems to do exactly what I and some other folks are wanting in this issue:
```console
$ cd ~/code/direnv/test

$ echo 'export testdir_var=foo' > .envrc
direnv: error /Users/tim.vergenz/code/direnv/test/.envrc is blocked. Run `direnv allow` to approve its content

$ direnv allow
direnv: loading ~/code/direnv/test/.envrc
direnv: export +testdir_var

$ echo 'export rootdir_var=bar' > ../.envrc

$ ( echo && echo 'eval "$(env -uDIRENV_{DIR,FILE,WATCHES,DIFF} -C.. direnv export bash)"' ) >> .envrc
direnv: error /Users/tim.vergenz/code/direnv/test/.envrc is blocked. Run `direnv allow` to approve its content

$ direnv allow
direnv: loading ~/code/direnv/test/.envrc
direnv: error /Users/tim.vergenz/code/direnv/.envrc is blocked. Run `direnv allow` to approve its content
direnv: export +testdir_var

$ direnv allow ..
direnv: loading ~/code/direnv/test/.envrc
direnv: loading ~/code/direnv/.envrc
direnv: export +rootdir_var
direnv: export +rootdir_var +testdir_var

$ cd ..
direnv: loading ~/code/direnv/.envrc
direnv: export +rootdir_var

$ cd ..
direnv: unloading
```

**Comment by rohanliston** [comment]
I just bumped into this issue as well and was surprised that `source_env` doesn't check the sourced env file.

For context, I wanted to set up direnv within my project as follows:
* An `.envrc` checked into the repo containing non-secret variables that need to be set for the project to work (e.g. URLs)
* An `.envrc.secrets` that is added to `.gitignore` for adding credentials and loaded in using `source_env`.

Happy to change strategy if there's a better way to achieve the above, where some variables are secret and others aren't.

**Comment by mattieb** [comment]
https://github.com/direnv/direnv/issues/249#issuecomment-1322602805

> ```shell
> source_up_secure() {
>   eval "$(env -uDIRENV_{DIR,FILE,WATCHES,DIFF} -C.. direnv export bash)" # https://github.com/direnv/direnv/issues/249#issuecomment-1322602805
> }
> ```

That's awesome, @vergenzt! I made one little tweak so it works with macOS's env, which doesn't support the -C flag:

```shell
source_up_secure() {
  eval "$(cd .. && env -uDIRENV_{DIR,FILE,WATCHES,DIFF} direnv export bash)"
}
```

I use Zsh, but "export bash" seems to work fine.

**Comment by vergenzt** [comment]
> https://github.com/direnv/direnv/issues/249#issuecomment-1322602805
> 
> 
> 
> > ```shell
> 
> > source_up_secure() {
> 
> >   eval "$(env -uDIRENV_{DIR,FILE,WATCHES,DIFF} -C.. direnv export bash)" # https://github.com/direnv/direnv/issues/249#issuecomment-1322602805
> 
> > }
> 
> > ```
> 
> 
> 
> That's awesome, @vergenzt! I made one little tweak so it works with macOS's env, which doesn't support the -C flag:
> 
> 
> 
> ```shell
> 
> source_up_secure() {
> 
>   eval "$(cd .. && env -uDIRENV_{DIR,FILE,WATCHES,DIFF} direnv export bash)"
> 
> }
> 
> ```

Nice! Thanks for the improvement.

> I use Zsh, but "export bash" seems to work fine.

FYI this needs to be "export bash" regardless of what shell you ultimately use, because IIUC direnv only *evaluates* .envrc files in bash (even though it can export the the results to other shells).

**Comment by vergenzt** [comment]
Hey all, FYI I filed #1556 to add a `source_up_secure` implementation to the standard library. 🙂
