### ISSUE TITLE
compilation requires use of GOPATH folder

### ISSUE THREAD

**Issue by ssbarnea** [direnv/direnv#283]
It seems that current compilation requires use of GOPATH folder when in reality it should be not more than `git checkout && make install`.

**Comment by punitagrawal** [comment]
I'm not sure if this is the same issue but recently when trying to upgrade the debian package to 2.12.2 I ran into the following error -

make[1]: Entering directory '/<<PKGBUILDDIR>>'
go fmt
go build  -o direnv
cmd_dotenv.go:7:2: cannot find package "github.com/direnv/direnv/dotenv" in any of:
        /usr/lib/go-1.8/src/github.com/direnv/direnv/dotenv (from $GOROOT)
        /sbuild-nonexistent/go/src/github.com/direnv/direnv/dotenv (from $GOPATH)
Makefile:36: recipe for target 'direnv' failed
make[1]: *** [direnv] Error 1
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
dh_auto_build: make -j1 returned exit code 2
debian/rules:8: recipe for target 'build-arch' failed
make: *** [build-arch] Error 2
dpkg-buildpackage: error: debian/rules build-arch gave error exit status 2

On further digging, I found that this is due to the import of "github.com/direnv/direnv/dotenv" in cmd_dotenv.go. 

Changing the above import to "./dotenv" makes it build for me but I'm not sure that is the right way to solve this problem. I am not familiar with go best practices but a bunch of commentary on the web suggests using relative path is a bad idea (not sure why).

I would really appreciate any input on the best way to make this build in a packaged environment without creating arbitrary directories.

**Comment by yermulnik** [comment]
@punitagrawal ain't this is the same as https://github.com/direnv/direnv/issues/277 that I encountered some time ago?

**Comment by punitagrawal** [comment]
Thanks for the pointer @yermulnik. That's the same problem.

I think the requirement for modules to be available at $GOPATH/src/github.com/direnv/direnv makes it awkward for distro packaging. But then I can't be the first person to be hitting this in debian. I'll look around to see what other packages are doing.

In the short term, the linked issue seems to suggest being able to use symlinks. I'll see if I can play tricks with that and upgrade the package version.

**Comment by zimbatm** [comment]
ce9945a8888ead47652b9a6f4acbca3a39c48528 reverts back to the original ways of doing it. by moving the dotenv dependency under the vendor/ folder, go should automatically pick it up and not require to set the GOPATH anymore.

**Comment by yermulnik** [comment]
@zimbatm Is there something I'm missing?
```
$> LANG=C git clone https://github.com/direnv/direnv
Cloning into 'direnv'...
remote: Counting objects: 2614, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 2614 (delta 1), reused 10 (delta 1), pack-reused 2600
Receiving objects: 100% (2614/2614), 1.24 MiB | 302.00 KiB/s, done.
Resolving deltas: 100% (1330/1330), done.
Checking connectivity... done.
$> cd ./direnv/
$> LANG=C make
go fmt
go build  -o direnv
cmd_dotenv.go:7:2: cannot find package "github.com/direnv/go-dotenv" in any of:
        /usr/lib/go-1.6/src/github.com/direnv/go-dotenv (from $GOROOT)
        ($GOPATH not set)
make: *** [direnv] Error 1
$>
```

**Comment by zimbatm** [comment]
It's not searching in the vendor/ folder for some reason. Can you try again
with the latest from master?

**Comment by yermulnik** [comment]
The same =(
```
$> LANG=C git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
$> LANG=C make
go fmt
go build  -o direnv
cmd_dotenv.go:7:2: cannot find package "github.com/direnv/go-dotenv" in any of:
        /usr/lib/go-1.6/src/github.com/direnv/go-dotenv (from $GOROOT)
        ($GOPATH not set)
make: *** [direnv] Error 1
```

**Comment by zimbatm** [comment]
It looks like it's an issue with go 1.6. According to https://github.com/golang/go/issues/14566 , go 1.6 only uses the vendor/ folder when it's under the GOPATH. Under go 1.9 it's fine so it has been fixed along the way.

**Comment by yermulnik** [comment]
I see. Thanks for the pointer. I indeed have Go 1.6.
Worked around this issue by symlinking `src` to `vendor` and using cmd to build: `GOPATH=$(pwd) make` =)

**Comment by cjsimon** [comment]
I have the same issue on OS X go version 1.9.2

`$ make install
go fmt
go build -ldflags ' -linkmode=external' -o direnv
cmd_dotenv.go:7:2: cannot find package "github.com/direnv/go-dotenv" in any of:
	/usr/local/go/src/github.com/direnv/go-dotenv (from $GOROOT)
	/Users/administrator/go/src/github.com/direnv/go-dotenv (from $GOPATH)
make: *** [direnv] Error 1`
