### ISSUE TITLE
Load/Unload Hooks

### ISSUE THREAD

**Issue by josephbuchma** [direnv/direnv#285]
What about running some arbitrary code on load/unload events?

## Usecase
I have multiple GOPATHs, and it would be cool if direnv would start `godoc` server automatically on loading, and stop it on unloading when I traverse between my GOPATHs (yes, I do work with one GOPATH at the time)

## Security
This hooks probably should not be stored in `.envrc`, or if stored, direnv should ask if user is aware of them at least once.

**Comment by zimbatm** [comment]
Hi @josephbuchma,

this has come up already but there are two issues which are related and don't have a clear solution to me.

If the terminal is exited uncleanly, the `godoc` process would stay started as well. direnv is not a process manager in that regard.

Relatedly, what happens if two terminals are opened at once? Which one gets to control the `godoc` process?

**Comment by josephbuchma** [comment]
Yeah, "unclean" exits might be a problem. But the rest can be handled inside those hooks. Like killing existing godoc process if there is any on given port before starting new one. Hmm... Maybe unload hook is not really needed :)
Applications here are endless, it's not only about starting some servers.

**Comment by zimbatm** [comment]
If the unload hook is unneeded then it's already possible to write something like that in the `.envrc`:

```sh
killall godoc
nohup godoc
```

The issue is that if there are two shells, opening two different project, the last-one will win. To switch to the older project run `direnv reload` in the older project.

**Comment by josephbuchma** [comment]
That might work for me, thanks @zimbatm
