### ISSUE TITLE
Regression: fail if uninitialized variables are being used breaks a lot of scripts

### ISSUE THREAD

**Issue by rjcoelho** [direnv/direnv#566]
Hi to all, https://github.com/direnv/direnv/commit/c70f7cddca922e830c6225833e4d736327d8bf7e breaks a lot of scripts. I'm kerl activating and it broke it. We should be aware of this when making such changes. 

Please add it as a direvn's op-in, since AFAIK that is the default behaviour for bash/zsh shell.

**Comment by zimbatm** [comment]
Can you give me a list of things that are breaking so I can gauge how much of a problem it is?

**Comment by Mellbourn** [comment]
@zimbatm No, we can't give you such a list, because this setting, `set -u`, affects the running of the scripts that we as _users_ of `direnv` have written for `direnv` to run.
That is why this is "breaks a lot of scripts"

**Comment by halostatue** [comment]
@zimbatm The problem isn’t as much shell scripts that are part of the standard library, but the cascading effect that `set -u` has on shell scripts that are _sourced_ (e.g., kerl, kiex, and chruby). There is a workaround, but it requires people to update their `.direnvrc`. For example, you’d have to change the first `use_kerl` implementation in the [Erlang](https://github.com/direnv/direnv/wiki/Erlang) entry on the Wiki to be this:

```sh
use_kerl () {
    set +u
    . $KERL_DEFAULT_INSTALL_DIR/$1/activate
    set -u
}
```

The third-party tools here that require `source`ing instead of calling an external sub-shell tool are broken by the stdlib use of `set -u`.

**Comment by halostatue** [comment]
This could be "fixed" if we added an `unsafe_source` function to the stdlib that basically does the following:

```sh
unsafe_src () {
    set +u
    source "$1"
    set -u
}
```

**Comment by zimbatm** [comment]
Okay, thanks for sharing the use-cases with me.

A quick workaround is to add `set +u` in the top of the direnvrc while I think more about this.

My hope was to update everyone to use safer scripts by default but I understand that it can be quite disruptive to your workflow.

**Comment by halostatue** [comment]
I’m adding this to my `.direnvrc`:

```sh
unsafe() {
  local res

  set +u

  "${@}"

  res=${?}
  set -u

  return "${res}"
}
```

It would be used as `unsafe source path-to-file`. It will work with any single-line command. I’m choosing to do this because `chruby` also executes in an “unsafe” manner, so I can also do `unsafe chruby ${1}`, as an example.

**Comment by zimbatm** [comment]
nice bernstein chaining :)

**Comment by halostatue** [comment]
I use this _all_ the time in my bash scripting. `when-ci fail-unless make ci`: if we’re on a CI server, fail _unless_ `make ci` works.

I do `fail-unless` because I find that `set -eo pipefail` is _way_ too aggressive (not everything that returns nonzero should be a failure, and shouldn’t necessarily be masked with `|| true`).

**Comment by zimbatm** [comment]
https://github.com/direnv/direnv/releases/tag/v2.21.2 reverses the `set -euo pipefail` change. I will have to add it more gradually.

**Comment by halostatue** [comment]
@zimbatm Would you be interested in a PR that adds an `unsafe` function to the stdlib of the sort described above? That would allow you to introduce this with a easy workaround that is readily available. If that’s added to the `stdlib` we can talk about updating the Wiki examples to call some of these things `unsafe`.

**Comment by zimbatm** [comment]
Sounds good. I was thinking of adding a `strict_env` config option to turn `set -euo pipefail` back on. That would be a good combo to it.

**Comment by zimbatm** [comment]
maybe name it `unstrict`? I don't know that bash scripts are ever safe :D
