### ISSUE TITLE
unexpected end of file when running eval $(direnv hook bash)

### ISSUE THREAD

**Issue by ouchxp** [direnv/direnv#663]
**Describe the bug**
Run `eval $(direnv hook bash)` getting error `bash: syntax error: unexpected end of file`

**To Reproduce**
`eval $(direnv hook bash)`

**Expected behavior**
the command should be executed successfully

**Environment**
 - OS:  macOS catalina
 - Shell: bash
 - Direnv version 2.21.3

**Comment by chrisbarrett** [comment]
Paired on this one and resolved it--it was an unexpected interaction between `use nix`, nix-shell (which uses bash) and the host shell (zsh). 

In particular, a `shell.nix` was defined with a shellHook to set up direnv, in case someone actually wanted to drop into the nix shell. It looks like this code ended up getting invoked in zsh, rather than the nix-shell (bash) environment. Somehow. I dunno. I was weird.

**Comment by zimbatm** [comment]
Ok. One detail: always make sure to quote the output of commands to avoid expansion:
```
eval $(direnv hook bash)
```
=>
```
eval "$(direnv hook bash)"
```
