### ISSUE TITLE
Possible to automatically allow?

### ISSUE THREAD

**Issue by introom** [direnv/direnv#766]
After editting .envrc, I have to manually direnv allow.

While automatically allowing envrc might expose a security hole, I wonder if it is possible to automatically allow envrc ?

**Comment by zimbatm** [comment]
`direnv edit` does something like that. First, you have to make sure that the EDITOR environment variable is set. Eg: `export EDITOR=vim`. Set that in your `~/.profile` or other startup location. Then instead of using `vim .envrc`, use `direnv edit`. Once the editor exits, and IFF the file mtime has changed, it assumes that you trust the content and will automatically allow it.

**Comment by introom** [comment]
It would be more preferable to have a variable to explicitly allow that behavior.

**Comment by nandalopes** [comment]
You may add the path to the direnv.toml config, see `man direnv.toml`

**Comment by introom** [comment]
Thanks for that.

**Comment by guettli** [comment]
Related question: https://github.com/orgs/direnv/discussions/1115
