### ISSUE TITLE
use_flake is pointing to the wrong nix version

### ISSUE THREAD

**Issue by jaybutera** [direnv/direnv#859]
When I upgraded to direnv v2.29.0, my envrc files containing `use flake` produce this output

```
error: 'print-dev-env' is not a recognised command
Try '/nix/store/ziybs0ldg2sdbk5pcxwzmlx26vk68q04-nix-2.3.16/bin/nix --help' for more information.
error: 'flake' is not a recognised command
Try '/nix/store/ziybs0ldg2sdbk5pcxwzmlx26vk68q04-nix-2.3.16/bin/nix --help' for more information.
```

for some reason it is using nix-2.3.16. I noticed that v2.29.0 added use_flake to the stdlib so I thought maybe direnv was explicitly referring to an old nix version.

I changed my envrc file to `use myflake` and the corresponding shell function in `~/.config/direnv/lib/use_flake.sh` and now direnv is working as expected again.

**Environment**
 - OS: nixos
 - Shell: zsh
 - Direnv version v2.29.0

**Additional context**
I'm using a flake for my nixos configuration, pointing to the 21.11 channel.

**Comment by zimbatm** [comment]
If you run `direnv stdlib | less` and search for use_flake, you should see that it's using nix from the environment.

Is the .envrc containing anything else than `use_flake`? What output do you get form `readlink -f $(type -p nix)`?

**Comment by nsaritzky** [comment]
Take a look at [this issue](https://github.com/nix-community/nix-direnv/issues/122) in nix-direnv. NixOS 21.11 still uses Nix 2.3, which has flakes disabled by default. Home-manager apparently had a mix-up and removed the programs.direnv.enableFlakes option assuming in their own 21.11 channel assuming the contrary. Home-manager has since reverted the change. I fixed it on my Mac by making sure that I was on a commit of home-manager that included that reversion (linked in the issue).

**Comment by zimbatm** [comment]
Thanks. I think this can be closed then.
