### ISSUE TITLE
A file gets created with part of the password

### ISSUE THREAD

**Issue by tonsV2** [direnv/direnv#934]
**Background**

In my .env file I have a password defined as below

    DATABASE_PASSWORD=blabla-and-other-chars>D666W

**The problem**

I started noticing a file in the root of my project called D666W and when I search the project I found a match in the .env file. I changed some characters and soon after a new file with the new characters was created.

**To Reproduce**

It's been a while since I've noticed this behaviour and I've tried to reproduce it a few times without luck which I why I haven't submitted this report before.

**Expected behavior**

No files should be created and  especially not with a name matching part of my password.

**Environment**
 - OS: Fedora 35
 - Shell: fish
 - Direnv version: e.g. 2.28.0

**Comment by niodice** [comment]
I'm not a maintainer of this project, but this appears to be an issue with your command and not the tool.

Try pasting that same statement into your `fish` shell. You'll likely see that file created on your filesystem (at least I do using `bash`).

You can consider properly escaping the password value to solve this:

`DATABASE_PASSWORD="blabla-and-other-chars>D666W"`
instead of
`DATABASE_PASSWORD=blabla-and-other-chars>D666W`

**Comment by tonsV2** [comment]
That would result in and error. And the file isn't created.

```
$ DATABASE_PASSWORD=blabla-and-other-chars>D666W
fish: Unsupported use of '='. In fish, please use 'set DATABASE_PASSWORD blabla-and-other-chars'.
```

**Comment by zimbatm** [comment]
I'm not able to reproduce the issue with fish 3.3.1 and direnv 2.31.0
