### ISSUE TITLE
Already exported environment variable is not updated

### ISSUE THREAD

**Issue by philipGaudreau** [direnv/direnv#988]
**Describe the bug**
An environment variable is not exported (updated) when I enter a project which changes its value. The variable is `SHELL`.

**To Reproduce**
1. Define a `.envrc` in a project with
```sh
export SHELL=<a shell that is not your default shell (other value than $SHELL, for example if $SHELL is `/usr/bin/fish`, set it to `/bin/bash`)>
```
2. run `direnv allow .` in project.

**Expected behavior**
The environment variable should now be different from the old one, but it is still the same.

**Environment**
 - OS: Ubuntu 20.04
 - Shell: fish
 - Direnv version: 2.32.1
 - Same behaviour inside and outside TMUX

**Comment by zimbatm** [comment]
SHELL is one of those environment variables that we don't want to touch because it has some unexpected side-effects. The host shell is responsible for handling it.

The list is available here: https://github.com/direnv/direnv/blob/2131cf24ed190bcfae3bcc6c8410ec7124e888d7/internal/cmd/env_diff.go#L11-L27
